DROP TABLE TB_MEMBER;
DROP TABLE TB_PROFESSOR;
DROP TABLE TB_COURSE;
DROP TABLE TB_COURSE_TIME;
DROP TABLE TB_COURSE_TIME_TABLE;


-- 멤버
CREATE TABLE `tb_member` (
	`MEMBER_IDX` BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT '멤버 SEQ',
	`MEMBER_ID` VARCHAR(40) NOT NULL COMMENT '멤버 ID',
	`MEMBER_PWD` VARCHAR(100) NOT NULL COMMENT '멤버 비밀번호',
	`MEMBER_NAME` VARCHAR(30) NOT NULL COMMENT '멤버 이름',
	`MEMBER_AVAILABLE_SCORE` INT(11) NOT NULL COMMENT '멤버의 최대 수강 가능 학점',
	`MEMBER_MIN_SCORE` INT(11) NOT NULL COMMENT '멤버 필수 수강 학점',
	PRIMARY KEY (`MEMBER_IDX`)
)
COMMENT='학생 정보'
COLLATE='utf8_general_ci'
ENGINE=InnoDB
;

-- 교수
CREATE TABLE `tb_professor` (
	`PROFESSOR_IDX` BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT '교수 SEQ',
	`PROFESSOR_NAME` VARCHAR(30) NOT NULL COMMENT '교수 이름',
	PRIMARY KEY (`PROFESSOR_IDX`)
)
COMMENT='교수 정보'
COLLATE='utf8_general_ci'
ENGINE=InnoDB
;

-- 수업 정보
CREATE TABLE `tb_course` (
	`COURSE_IDX` BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT '수업 SEQ',
	`PROFESSOR_IDX` BIGINT(20) NOT NULL COMMENT '교수 SEQ',
	`COURSE_NAME` VARCHAR(50) NOT NULL COMMENT '수업명',
	`COURSE_SCORE` INT(11) NOT NULL COMMENT '수업 학점',
	PRIMARY KEY (`COURSE_IDX`),
	INDEX `COURSE_KEY_PROFESSOR` (`PROFESSOR_IDX`),
	CONSTRAINT `COURSE_KEY_PROFESSOR` FOREIGN KEY (`PROFESSOR_IDX`) REFERENCES `tb_professor` (`PROFESSOR_IDX`) ON DELETE NO ACTION
)
COMMENT='수업 정보'
COLLATE='utf8_general_ci'
ENGINE=InnoDB
;


-- 수업 별 시간
CREATE TABLE `tb_course_time` (
	`COURSE_TIME_IDX` BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT '수업 별 시간 SEQ',
	`COURSE_IDX` BIGINT(20) NOT NULL COMMENT '수업 정보 SEQ',
	`COURSE_TIME_INFO` VARCHAR(50) NOT NULL COMMENT '수업 별 시간 상세정보',
	PRIMARY KEY (`COURSE_TIME_IDX`),
	INDEX `COURSE_TIME_KEY_COURSE` (`COURSE_IDX`),
	CONSTRAINT `COURSE_TIME_KEY_COURSE` FOREIGN KEY (`COURSE_IDX`) REFERENCES `tb_course` (`COURSE_IDX`) ON DELETE CASCADE
)
COMMENT='수업 별 시간'
COLLATE='utf8_general_ci'
ENGINE=InnoDB
;


-- 수업 별 시간 정보
CREATE TABLE `tb_course_time_table` (
	`COURSE_TIME_IDX` BIGINT(20) NOT NULL COMMENT '수업 별 시간 SEQ',
	`TIME_TABLE_DAY` INT(11) NOT NULL COMMENT '수업 시작 요일',
	`TIME_TABLE_START` INT(11) NOT NULL COMMENT '수업 시작 교시',
	`TIME_TABLE_END` INT(11) NOT NULL COMMENT '수업 종료 교시',
	INDEX `TIME_TABLE_KEY_COURSE_TIME` (`COURSE_TIME_IDX`),
	CONSTRAINT `TIME_TABLE_KEY_COURSE_TIME` FOREIGN KEY (`COURSE_TIME_IDX`) REFERENCES `tb_course_time` (`COURSE_TIME_IDX`) ON DELETE CASCADE
)
COMMENT='수업 시간 시간정보'
COLLATE='utf8_general_ci'
ENGINE=InnoDB
;


-- 수강 등록 정보
CREATE TABLE `TB_REGISTER_COURSE` (
	`REGISTER_IDX` BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT '수업신청 SEQ',
	`MEMBER_IDX` BIGINT(20) NOT NULL COMMENT '멤버 SEQ',
	`COURSE_TIME_IDX` BIGINT(20) NOT NULL COMMENT '수업 별 시간 SEQ',
	`REGISTER_DATE` DATETIME NOT NULL COMMENT '등록일',
	PRIMARY KEY (`REGISTER_IDX`),
	INDEX `REGISTER_COURSE_KEY_MEMBER_IDX` (`MEMBER_IDX`),
	INDEX `REGISTER_COURSE_KEY_COURSE_IDX` (`COURSE_TIME_IDX`),
	CONSTRAINT `REGISTER_COURSE_KEY_COURSE_IDX` FOREIGN KEY (`COURSE_TIME_IDX`) REFERENCES `tb_course_time` (`COURSE_TIME_IDX`),
	CONSTRAINT `REGISTER_COURSE_KEY_MEMBER_IDX` FOREIGN KEY (`MEMBER_IDX`) REFERENCES `tb_member` (`MEMBER_IDX`)
)
COMMENT='학생들의 수업신청 내역'
COLLATE='utf8_general_ci'
ENGINE=InnoDB
;

